### ISSUE TITLE
Explain why we think this won't become boilerplate in every source file

### ISSUE THREAD

**Issue by domenic** [domenic/proposal-function-implementation-hiding#10]
Namely, that this is purely about encapsulation, and if it became e.g. a memory win, we'd immediately implement a different (out of band) app-wide mechanism.

**Comment by domenic** [comment]
Yeah, that's a separate proposal that would build on the HostHasSourceTextAvailable. But, right now those engines don't need it, and browser JS engines don't have the engineering resources to make it work, so it's on pause.

**Comment by isiahmeadows** [comment]
Okay. It was just a thought. My implication was that this would be "implementation-defined" rather than "host-defined", so engines have the choice, not the embedder (unless, of course, engines exposed that to the embedder).

**Comment by domenic** [comment]
I meant to send https://github.com/domenic/proposal-function-implementation-hiding/commit/510c44345808492f07f06adffa642940354d056d as a pull request, oops. It makes statements about encapsulation and uses the term "we" which I would feel better getting co-champion sign-off on.

@michaelficarra or others, please let me know if https://github.com/domenic/proposal-function-implementation-hiding/commit/510c44345808492f07f06adffa642940354d056d needs any tweaks.
