### ISSUE TITLE
Explain more why pragma is the best fit

### ISSUE THREAD

**Issue by domenic** [domenic/proposal-function-implementation-hiding#9]
@erights, @mikesamuel, and @waldemarhorwat all had points I will try to jot down:

- Pragmas offer a unique syntactic space in that they are lexical and they are backward-compatible
- Tooling (e.g. an inliner) that wants to treat censored functions differently requires lexical source code information, not runtime information. (Compare to `.censor()` alternative.)
- ... I forget Waldemar's point :(

**Comment by mikesamuel** [comment]
+1

I would like to avoid inliners having to use heuristics to decide whether they can inline a call to a potentially censored function into a potentially uncensored function's body.
